
int get_number_of_areas (void);
const char *yn (int yn);
char *Notify (const char *s);
void BoxInput (const char *title, char *stash, int length);
void read_wwivtoss_config (void);
void read_wwiv_config (void);
void write_wwivtoss_config (void);
void read_domain_config (void);
void write_domain_config (void);
void read_nodes_config(void);
void write_nodes_config (void);
void read_uplink_config(void);
void write_uplink_config (void);
void init_areas_config(void);
char *mailer_type_string (int mailer_type);
const char *packet_type_string (int packet_type);
char *area_type_string (int area_type);
void write_area (long un, arearec * a);
void read_area (long un, arearec * a);
void print_wwivtoss_config ();
void display_main ();
void display_title (const char *title);
void display_area (long i);
void display_node(int nodenum);
void edit_node(int nodenum);
void display_uplink(int nodenum);
void AreaManager ();
void SetUpScreen ();
void SiteInfo ();
void NetworkAddresses ();
void Groups ();
void PathSetup ();
void edit_archiver (int i);
void ArchiverSetup ();
void UplinkManager ();
void SystemData ();
void MiscOptions ();
void NodeManager ();
void edit_route (int i);
void RouteManager ();
void TranslationTables ();
void ExportManager ();
void MakeSubsLsts ();
void AboutWWIVTOSS ();
void CheckPassword ();
void sort_areas();
void write_area2 (long un, arearec * a);
